
server:
  address: 0.0.0.0  # 监听所有网络接口（局域网可访问）
  port: 8080        # 指定端口（可选，默认8080）
  ssl:
    enabled: true
    key-store-type: JKS
    key-store-password: 123456
    key-store: classpath:boothttps.jks

spring:


  redis:
    host: 192.168.221.135  # Redis服务器地址
    port: 6379       # Redis服务器连接端口
    password:        # Redis服务器连接密码（默认为空）
    database: 0      # Redis数据库索引（默认为0）
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8    # 连接池中的最大空闲连接
        min-idle: 0    # 连接池中的最小空闲连接
    timeout: 5000ms  # 连接超时时间（毫秒）



  datasource:
    driver-class-name: com.kingbase8.Driver
    username: SYSTEM
    password: 654321
# 开发环境url
    url: jdbc:kingbase8://frp-dog.com:30893/test?useUnicode=true&characterEncoding=UTF-8
# 生产环境url
#    url: jdbc:kingbase8://192.168.3.21:54321/test?useUnicode=true&characterEncoding=UTF-8

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

    jackson:
      deserialization:
        accept-case-insensitive-properties: true
        fail-on-unknown-properties: false


logging:
  level:
    com.proj: debug
  pattern:
    dateformat: HH:mm:ss
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true

