server:
  address: 0.0.0.0
  port: 8443
  ssl:
    enabled: true
    key-store-type: JKS
    key-store-password: 123456
    key-store: classpath:boothttps.jks

spring:

  # 【核心修改】新增 spring.session 配置块
  session:
    # 明确指定使用 redis 来存储 session
    store-type: redis
    # 可选：设置 session 在 redis 中的过期时间，例如30分钟
    timeout: 30m

  redis:
    host: frp-dog.com
    port: 47971
    password:
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 5000ms

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

      client:
        registration:
          oidc-client:
            provider: spring-auth-server
            client-id: oidc-client
            client-secret: secret
            authorization-grant-type: authorization_code
            # 【核心修改】明确指定重定向URI模板
            # Spring Boot会自动将 {baseUrl} 替换为 https://localhost:8080
            # 并将 {registrationId} 替换为 oidc-client
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, read, write
        provider:
          spring-auth-server:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            jwk-set-uri: http://localhost:9000/oauth2/jwks

  datasource:
    driver-class-name: com.kingbase8.Driver
    username: SYSTEM
    password: 654321
    url: jdbc:kingbase8://frp-dog.com:30893/test?useUnicode=true&characterEncoding=UTF-8

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
    jackson:
      deserialization:
        accept-case-insensitive-properties: true
        fail-on-unknown-properties: false

logging:
  level:
    com.proj: debug
  pattern:
    dateformat: HH:mm:ss

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
