#spring:
#  datasource:
#    url: jdbc:mysql://192.168.221.131/mydb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123
#spring:
#  application:
#    name: oauth-server
#  datasource:
#    jdbc-url: jdbc:kingbase8://192.168.221.133:54321/mydb?useUnicode=true&characterEncoding=UTF-8
#    #    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.kingbase8.Driver
#    username: SYSTEM
#    password: 123456


spring:
  datasource:
    driver-class-name: com.kingbase8.Driver
    username: SYSTEM
    password: 123456

#spring:
#  datasource:
#    driver-class-name: com.kingbase8.Driver
#    username: SYSTEM
#    password: 123456

    url: jdbc:kingbase8://192.168.31.87:54321/test?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:kingbase8://192.168.221.135:54321/mydb?useUnicode=true&characterEncoding=UTF-8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

logging:
  level:
    com.proj: debug
  pattern:
    dateformat: HH:mm:ss
mybatis:
  mapper-locations: classpath*:mapper/*.xml
server:
  port: 8081