
server:
  address: 0.0.0.0  # 监听所有网络接口（局域网可访问）
  port: 8080        # 指定端口（可选，默认8080）

spring:
  datasource:
    driver-class-name: com.kingbase8.Driver
    username: SYSTEM
    password: 654321

    url: jdbc:kingbase8://192.168.3.21:54321/test?useUnicode=true&characterEncoding=UTF-8

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB


logging:
  level:
    com.proj: debug
  pattern:
    dateformat: HH:mm:ss
mybatis:
  mapper-locations: classpath*:mapper/*.xml
